### PR TITLE
Oauth

### PR DESCRIPTION
**Pull request by jshin49**
- Added ionic.css back to index.html
- Removed Facebook icon from landing page
- Added basic FB login function (needs unit_testing and redirecting and fetching user data)

### CODE REVIEW

**Comment by linhnta925** [comment]
Hi @jshin49, have you tested whether the login code works?

**Comment by jshin49** [comment]
i forgot to push some more commits yesterday. will do after lunch

**Comment by jshin49** [comment]
Can you merge now? Why is it blocked?

**Review by linhnta925 — APPROVED** [review]
Good, I'll merge now

**Pull request merged**
