### PR TITLE
Landing Page Design

### PR DESCRIPTION
**Pull request by jshin49**
Initial Landing Page Design

### CODE REVIEW

**Comment by jshin49** [comment]
I accidentally pushed all the bower libs to the repo because there were no mention about that in the gitignore file.

I believe the commit that Deleted every bower lib on my branch won't affect the master branch because there were none from the beginning in the master branch.

**Review by linhnta925 — CHANGES_REQUESTED** [review]
Hi @jshin49, there's no need to comment uncessary libs in the **www/index.html** file as they don't cause any error.

Unless you add new libs, just keep other libs there

**Comment by linhnta925** [comment]
@jshin49 Don't worry about Bower lib, according to Github, there is no conflict 👍

**Comment by linhnta925** [comment]
Hi @jshin49, there's no need to comment uncessary libs in the **www/index.html** file as they don't cause any error.

Unless you add new libs, just keep other libs there

**Comment by jshin49** [comment]
Fixed index.html but left some comments for readability

**Pull request merged**
