### PR TITLE
Page redirection when no user signing in

### PR DESCRIPTION
**Pull request by linhnta925**
#14

### CODE REVIEW

**Comment by jshin49** [comment]
Why change /login to /signin?

Won't it just cause confusion to the rest?

**Comment by linhnta925** [comment]
I just want to make it more similar to the Firebase API (Firebase uses the term "sign in")
Does it affect your authentication code?

**Comment by jshin49** [comment]
Not for me, but I think it's better to stick with /login because everyone else has /login in their code. It's an unnecessary change. Other than that, I think we should merge it.

**Comment by linhnta925** [comment]
I see.
Will change it tonight

**Comment by linhnta925** [comment]
Hi everyone, please DO NOT MERGE THIS PULL REQUEST BEFORE FINISHING OTHER FEATURES OF OUR APPS.

Otherwise, we will have to constantly do "sign in" to do unit testing

**Pull request merged**
